# Eat Safe, Love

## Notebook Set Up

In [1]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database

db.list_collection_names()

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [6]:
 # Do an analysis of the contents of establishments for later compute
sample_documents = establishments.find().limit(2) 

print("Sample Documents from Establishments Collection:")
for doc in sample_documents:
    pprint(doc)

Sample Documents from Establishments Collection:
{'AddressLine1': '23 The Stade',
 'AddressLine2': 'Folkestone',
 'AddressLine3': 'Kent',
 'AddressLine4': '',
 'BusinessName': 'The Ship',
 'BusinessType': 'Pub/bar/nightclub',
 'BusinessTypeID': 7843,
 'ChangesByServerID': 0,
 'Distance': 4591.912144538092,
 'FHRSID': 289352,
 'LocalAuthorityBusinessID': 'PI/000002460',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CT19 6AB',
 'RatingDate': '2015-08-27T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('677f617bc86f35e3ecb039ea'),
 'geocode': {'latitude': 51.08084, 'longitude': 1.188537},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/289352',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}
{'AddressLine1': 'East Cliff Pavilion',
 'AddressLine2': 'Wear Bay Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'BusinessName': 'The Pavilion',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4591.765489457773,
 'FHRSID': 1043695,
 'LocalAuthorityBusinessID': 'PI/000073616',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CT19 6BL',
 'RatingDate': '2018-04-04T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('677f617bc86f35e3ecb039ec'),
 'geocode': {'latitude': 51.083812, 'longitude': 1.195625},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1043695',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}

In [7]:
# Count total establishments in the collection
total_establishments_count = establishments.count_documents({}) 

# Print the total number of establishments
print(f"Total number of establishments in the database: {total_establishments_count}")

Total number of establishments in the database: 38786

In [8]:
# Find the establishments with a hygiene score of 20
hygiene_query = {"scores.Hygiene": 20}

# Use count_documents to display the number of documents in the result
hygiene_count = establishments.count_documents(hygiene_query)
print(f"Number of establishments with a hygiene score of 20: {hygiene_count}")

# Display the first document in the results using pprint
first_hygiene_establishment = establishments.find_one(hygiene_query)
print("First establishment with a hygiene score of 20:")
pprint(first_hygiene_establishment)

Number of establishments with a hygiene score of 20: 41
First establishment with a hygiene score of 20:
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('677f617bc86f35e3ecb0551b'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [9]:
# Convert the result to a Pandas DataFrame
results = establishments.find(hygiene_query)
establishments_df = pd.DataFrame(list(results))
# Display the number of rows in the DataFrame
print("Number of rows in the DataFrame:", len(establishments_df))
# Display the first 10 rows of the DataFrame

establishments_df.head(10)

Number of rows in the DataFrame: 41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,677f617bc86f35e3ecb0551b,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,http://www.eastbourne.gov.uk/foodratings,Customerfirst@eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.27694, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,677f617bc86f35e3ecb058a3,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 1.278721, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,677f617bc86f35e3ecb05bb5,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 1.15927, 'latitude': 51.789429}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,677f617bc86f35e3ecb05d96,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.10202, 'latitude': 50.770885}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,677f617bc86f35e3ecb05da5,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.101446, 'latitude': 50.770724}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
5,677f617bc86f35e3ecb0674b,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.736349, 'latitude': 51.541448}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
6,677f617bc86f35e3ecb06965,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.7121671, 'latitude': 51.5350065}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
7,677f617cc86f35e3ecb07e91,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,http://www.rochford.gov.uk,customerservices@rochford.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.602364, 'latitude': 51.591515}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,677f617cc86f35e3ecb082d3,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,http://www.sevenoaks.gov.uk/,environmental.health@sevenoaks.gov.uk,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.146449998021126, 'latitude': 5...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,677f617cc86f35e3ecb08ae6,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,http://www.basildon.gov.uk,ehs@basildon.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.462307, 'latitude': 51.57005}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

In [10]:
# Display the number of rows in the DataFrame
print("Number of rows in the DataFrame:", len(establishments_df))

#show just 3 columns of the Dataframe for better display
filtered_df = establishments_df[['BusinessName', 'BusinessType', 'BusinessTypeID']]
filtered_df.head(10)

Number of rows in the DataFrame: 41

,BusinessName,BusinessType,BusinessTypeID
0,The Chase Rest Home,Caring Premises,5
1,Brenalwood,Caring Premises,5
2,Melrose Hotel,Hotel/bed & breakfast/guest house,7842
3,Seaford Pizza,Takeaway/sandwich shop,7844
4,Golden Palace,Restaurant/Cafe/Canteen,1
5,Ashby's Butchers,Retailers - other,4613
6,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1
7,Golden Palace,Takeaway/sandwich shop,7844
8,The Tulip Tree,Restaurant/Cafe/Canteen,1
9,F & S,Retailers - other,4613

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [11]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {
    "LocalAuthorityName": {"$regex": "London", "$options": "i"},  
    "RatingValue": {"$gte": 4}  
}

# Use count_documents to display the number of documents in the result
london_count = establishments.count_documents(query)
print("Number of establishments in London with a RatingValue >= 4:", london_count)

# Display the first document in the results using pprint
first_london_establishment = establishments.find_one(query)
print("First establishment in London with a RatingValue >= 4:")
pprint(first_london_establishment)

Number of establishments in London with a RatingValue >= 4: 33
First establishment in London with a RatingValue >= 4:
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('677f617cc86f35e3ecb06f37'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [12]:
# Convert the result to a Pandas DataFrame
results = establishments.find(query)
establishments_df_2 = pd.DataFrame(list(results))
# Display the number of rows in the DataFrame
print("Number of rows in the DataFrame:", len(establishments_df_2))
# Display the first 10 rows of the DataFrame
print("First 10 rows of the DataFrame:")
establishments_df_2.head(10)

Number of rows in the DataFrame: 33
First 10 rows of the DataFrame:

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,677f617cc86f35e3ecb06f37,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': 0.508551, 'latitude': 51.369321}",,4627.439468,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,677f617cc86f35e3ecb0725f,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.249255999922752, 'latitude': 5...",,4627.873179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
2,677f617cc86f35e3ecb07dac,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.561954, 'latitude': 51.543831}",,4631.968418,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
3,677f617cc86f35e3ecb08bab,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.346336990594864, 'latitude': 5...",,4636.846754,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
4,677f617cc86f35e3ecb08bac,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.346325, 'latitude': 51.464078}",,4636.847650,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
5,677f617cc86f35e3ecb092c6,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.287555, 'latitude': 51.504071}",,4640.460834,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
6,677f617cc86f35e3ecb0b3cd,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.069286, 'latitude': 51.501121}",,4648.301822,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
7,677f617cc86f35e3ecb0b78b,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.048006, 'latitude': 51.503733}",,4649.173485,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,677f617cc86f35e3ecb0b79d,295107,0,PI/000020749,City Bar & Grill,Restaurant/Cafe/Canteen,1,London City Airport (Airside),London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0479655750095844, 'latitude': ...",,4649.188850,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,677f617cc86f35e3ecb0b7b1,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.047966, 'latitude': 51.504112}",,4649.188826,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

In [13]:
# Display the number of rows in the DataFrame
print("Number of rows in the DataFrame:", len(establishments_df_2))
#show just 3 columns of the Dataframe for better display
filtered_df2 = establishments_df_2[['BusinessName', 'BusinessType', 'BusinessTypeID']]
filtered_df2.head(10)

Number of rows in the DataFrame: 33

,BusinessName,BusinessType,BusinessTypeID
0,Charlie's,Other catering premises,7841
1,Mv City Cruises Erasmus,Other catering premises,7841
2,Benfleet Motor Yacht Club,Other catering premises,7841
3,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1
4,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1
5,Mv Valulla,Other catering premises,7841
6,Tereza Joanne,Other catering premises,7841
7,Brick Lane Brews,Restaurant/Cafe/Canteen,1
8,City Bar & Grill,Restaurant/Cafe/Canteen,1
9,The Nuance Group (UK) Limited,Retailers - other,4613

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [14]:
# Check that the new restaurant was inserted and retrieve its details
added_restaurant = establishments.find_one({"BusinessName": "Penang Flavours"})
print("Added restaurant details:")
pprint(added_restaurant)

# Step to extract latitude and longitude
if added_restaurant and 'geocode' in added_restaurant:
    latitude = added_restaurant['geocode'].get('latitude')
    longitude = added_restaurant['geocode'].get('longitude')
    print(f"Latitude of Penang Flavours: {latitude}")
    print(f"Longitude of Penang Flavours: {longitude}")
else:
    print("Geocode information is not available for Penang Flavours.")

Added restaurant details:
{'AddressLine1': 'Penang Flavours',
 'AddressLine2': '146A Plumstead Rd',
 'AddressLine3': 'London',
 'AddressLine4': '',
 'BusinessName': 'Penang Flavours',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'Distance': 4623.972328074718,
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': True,
 'Phone': '',
 'PostCode': 'SE18 7DY',
 'RatingValue': None,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('677f61c1c674e74da5513ade'),
 'geocode': {'latitude': 51.490142, 'longitude': 0.08384},
 'scores': {'ConfidenceInManagement': '', 'Hygiene': '', 'Structural': ''}}
Latitude of Penang Flavours: 51.490142
Longitude of Penang Flavours: 0.08384

In [15]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

# Define the query to find the restaurant
query_one = {'BusinessName': 'Penang Flavours'}

# Define the fields to project
fields_to_project = {
    'BusinessName': 1,
    'geocode.latitude': 1,  
    'geocode.longitude': 1
}

# Execute the query and fetch the relevant fields
result_one = establishments.find_one(query_one, fields_to_project)

degree_search = 0.01
query = {'RatingValue': 5,
         'geocode.latitude': {'$gte': (latitude - degree_search)},
         'geocode.latitude': {'$lte': (latitude + degree_search)},
         'geocode.longitude': {'$gte': (longitude - degree_search)},
         'geocode.longitude': {'$lte': (longitude + degree_search)},
         'scores.Hygiene': {'$ne': None}
         }

show = {'BusinessName': 1,'RatingValue': 1, 'scores.Hygiene':1, 'geocode.latitude': 1, 'geocode.longitude': 1}
sort=[('scores.Hygiene', 1)]
limit=5
result = establishments.find(query, show).sort(sort).limit(limit)


# Print the results
BusinessName_list=[]
RatingValue_list=[]
id_list=[]
latitude_list=[]
longitude_list=[]
hygiene_list=[]

for row in result:
    pprint(row)
    BusinessName= row['BusinessName']
    RatingValue= row['RatingValue']
    id= row["_id"]
    latitude= row['geocode']['latitude']
    longitude= row['geocode']['longitude']
    hygiene = row ['scores']['Hygiene']
    
    BusinessName_list.append(BusinessName)
    RatingValue_list.append(RatingValue)
    id_list.append(id)
    latitude_list.append(latitude)
    longitude_list.append(longitude)
    hygiene_list.append(hygiene)

{'BusinessName': 'Angies Newsagents',
 'RatingValue': 5,
 '_id': ObjectId('677f617bc86f35e3ecb05ef6'),
 'geocode': {'latitude': 50.77601, 'longitude': 0.093059},
 'scores': {'Hygiene': 0}}
{'BusinessName': 'Ab Fab Rooms',
 'RatingValue': 5,
 '_id': ObjectId('677f617bc86f35e3ecb05fd6'),
 'geocode': {'latitude': 50.780751, 'longitude': 0.083468},
 'scores': {'Hygiene': 0}}
{'BusinessName': 'Beachlands Care Home',
 'RatingValue': 5,
 '_id': ObjectId('677f617bc86f35e3ecb05f63'),
 'geocode': {'latitude': 50.775392, 'longitude': 0.088903},
 'scores': {'Hygiene': 0}}
{'BusinessName': 'Costcutter Claremont',
 'RatingValue': 5,
 '_id': ObjectId('677f617bc86f35e3ecb05ef7'),
 'geocode': {'latitude': 50.77601, 'longitude': 0.093059},
 'scores': {'Hygiene': 0}}
{'BusinessName': 'Clifden House Dementia Care Centre',
 'RatingValue': 5,
 '_id': ObjectId('677f617bc86f35e3ecb05f46'),
 'geocode': {'latitude': 50.776112, 'longitude': 0.089886},
 'scores': {'Hygiene': 0}}

In [16]:
# Convert result to Pandas DataFrame
result_df = pd.DataFrame({
        'BusinessName': BusinessName_list,
        'RatingValue': RatingValue_list,
        'Hygiene': hygiene_list,
        'Latitude': latitude_list,
        'Longitude': longitude_list
    })

result_df.head(5)

,BusinessName,RatingValue,Hygiene,Latitude,Longitude
0,Angies Newsagents,5,0,50.776010,0.093059
1,Ab Fab Rooms,5,0,50.780751,0.083468
2,Beachlands Care Home,5,0,50.775392,0.088903
3,Costcutter Claremont,5,0,50.776010,0.093059
4,Clifden House Dementia Care Centre,5,0,50.776112,0.089886

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [17]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest

pipeline = [
        {"$match": {"scores.Hygiene": 0}},
        {"$group": {"_id": "$LocalAuthorityName", "count": {"$sum": 1}}},
         {"$sort": {"count": -1}}  
         ]

# Print the number of documents in the result
results2 = list(establishments.aggregate(pipeline))
# Print the first 10 results
pprint(results2[0:10])

[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [19]:
# Convert the result to a Pandas DataFrame
new_df= pd.DataFrame(results2)

# Display the number of rows in the DataFrame
print("Number of rows in the DataFrame: ", len(results2))

# Display the first 5 rows of the DataFrame
new_df.head(5)

Number of rows in the DataFrame:  55

         _id  count
0     Thanet   1130
1  Greenwich    882
2  Maidstone    713
3     Newham    711
4      Swale    686